### ISSUE TITLE
Syncthing - Update to 1.20.1 and Addons stop working

### ISSUE THREAD

**Issue by letnic** [agileek/hassio-addons#38]
**Describe the bug**
addons doesn't run at all.

**To Reproduce**
Install addons and start it.

**Expected behavior**
addons doesn't run at all.

**Screenshots**
![image](https://user-images.githubusercontent.com/44958574/170174427-33e2a9f7-faea-4b2d-85bf-5c4c5dd9148c.png)

**Runtime (please complete the following information):**
 - Hardware: proxmox VM
 - OS: hassos 8.1
 - Architecture: x86
 - Home assistant version:  2022.5.5
 - Addon Version : 1.20.1

**Comment by kdorff** [comment]
I can second this report with my own.

**Which addon?**
syncthing

**Describe the bug**
After upgrading from 1.19.1 to 1.20.1, the logs show only `s6-overlay-suexec: fatal: can only run as pid 1`
Rolling back to 1.19.1 (using proxmox snapshots) brings syncthing back 1.19.1, which works.

**To Reproduce**

Notes:

- I'm **not** using the syncthing integration.
- I've repeated this 3 times with the same behavior.
- I am "up to date" with HA, HAOS, all other addons, etc.

Steps:

- Have syncthing addon 1.19.1 running.
- Look in `Settings | Addons | Syncthing | Logs` and see healthy log messages
- Take a snapshot with proxmox (so I can get back to a working system)
- upgrade syncthing to 1.20.1
- Look in `Settings | Addons | Syncthing | Logs` see  `s6-overlay-suexec: fatal: can only run as pid 1`
- Restart syncthing from Look in `Settings | Addons | Syncthing | Restart`
- Look in `Settings | Addons | Syncthing | Logs` see  `s6-overlay-suexec: fatal: can only run as pid 1`
- Reboot the VM with `Settings | System | Hardware | Reboot host`
- Wait for Reboot to complete to complete
- Look in `Settings | Addons | Syncthing | Logs` see  `s6-overlay-suexec: fatal: can only run as pid 1`
- Restart syncthing from `Look in Settings | Addons | Syncthing | Restart`
- Look in `Settings | Addons | Syncthing | Logs` see  `s6-overlay-suexec: fatal: can only run as pid 1`
- Rollback the snapshot with proxmox (so my system works again).
- Reboot the system
- Look in `Settings | Addons | Syncthing` and see that syncthing is again at 1.19.1 and wanting to be updated.
- Look in `Settings | Addons | Syncthing | Logs` and see healthy log messages

**Expected behavior**
Log messages that show syncthing starting up / running.

**Screenshots**
N/A.

**System**
Home Assistant Core 2022.5.5
Home Assistant Supervisor 2022.05.3
Home Assistant OS 8.1
Kernel version 5.15.41
Agent version 1.2.1
Hardware: proxmox VM
Architecture: x86
Addon Version : 1.20.1

**Comment by kdorff** [comment]
In the HA discord today (2022-05-25) at about 7:31pm (central time) in the `#add-ons` channel, user `Frenck` suggested the add-on's config was missing "init: false".

![syncthing-problem-possible-solution](https://user-images.githubusercontent.com/757170/170391982-1a27e5af-990d-43af-8bfa-151032ed4a2f.jpg)

**Comment by kevindorff** [comment]
This seems to describe the necessary change along with when and why

https://developers.home-assistant.io/blog/2022/05/12/s6-overlay-base-images/

**Comment by kdorff** [comment]
I believe the fix is to change `syncthing/config.json`

- update the version line  `"version": "1.20.1-1",`
- add the line `"init": false`

**Comment by kevdliu** [comment]
The signal addon probably needs the init: false change as well

**Comment by Veldkornet** [comment]
I have the same issue... 
`s6-overlay-suexec: fatal: can only run as pid 1`
before I found this thread though, I tried to do a rebuild of the addon, and then you get messages like this:

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
$HOME is not defined
panic: Failed to get user home dir
goroutine 1 [running]:
github.com/syncthing/syncthing/lib/locations.userHomeDir()
	github.com/syncthing/syncthing/lib/locations/locations.go:187 +0x88
github.com/syncthing/syncthing/lib/locations.init.0()
	github.com/syncthing/syncthing/lib/locations/locations.go:56 +0x20
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

**Comment by thefoxmangit** [comment]
I have exactly the same log output as @Veldkornet

**Comment by kdorff** [comment]
This is now fixed with 1.20.2 that is now released. This issue can be closed.

**Comment by thefoxmangit** [comment]
For me the issue persists also with 1.20.2, removed and reinstalled and still the output above posted by @Veldkornet in the logs

**Comment by letnic** [comment]
I have same log has @Veldkornet. The issue is still there.

**Comment by Veldkornet** [comment]
Strangely, mine is working after the latest update...

**Comment by letnic** [comment]
I'm now on 
System
Home Assistant Core 2022.6.5
Home Assistant Supervisor 2022.05.3
Home Assistant OS 8.1
Kernel version 5.15.41
Agent version 1.2.1
Hardware: proxmox VM
Architecture: x86
Addon Version : 1.20.2

I try rebuild, uninstall and reinstall and restart HA. Nothing is working.
Still same message has @Veldkornet 

``s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
$HOME is not defined
panic: Failed to get user home dir
goroutine 1 [running]:
github.com/syncthing/syncthing/lib/locations.userHomeDir()
	github.com/syncthing/syncthing/lib/locations/locations.go:187 +0x7d
github.com/syncthing/syncthing/lib/locations.init.0()
	github.com/syncthing/syncthing/lib/locations/locations.go:56 +0x1d
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped``

**Comment by thefoxmangit** [comment]
Tried a reinstall and rebuild as well, same problem:

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
$HOME is not defined
panic: Failed to get user home dir
goroutine 1 [running]:
github.com/syncthing/syncthing/lib/locations.userHomeDir()
	github.com/syncthing/syncthing/lib/locations/locations.go:187 +0x88
github.com/syncthing/syncthing/lib/locations.init.0()
	github.com/syncthing/syncthing/lib/locations/locations.go:56 +0x20
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by MichaelBitard** [comment]
I'm so sorry, I did not get notifications on this issue, I don't know why.

It still appears in 1.20.2?

**Comment by Veldkornet** [comment]
Mine has been working fine since I reported that it works, but strangely others are still having the issue.

**Comment by MichaelBitard** [comment]
I opened an issue to syncthing to see if that's something that could be fixed, and what changed recently (from what I saw, they went from the simple dash notation `-home` to the double dash `--home`, but with the env var set it should work...

Maybe some fork happens somewhere that does not preserve the env variable...

**Comment by MichaelBitard** [comment]
I tried something on the 1.20.2-1, could you try again? It (still) works on my setup, I hope it'll fix yours

**Comment by thefoxmangit** [comment]
Thank you so much, its working again!

**Comment by MichaelBitard** [comment]
Great news, and sorry again for not seeing this issue sooner. I'll close this as soon as @letnic confirms it works too

**Comment by letnic** [comment]
Sorry i was always from home. It's working now. Thank you for help.
